/* Script for generating a SRDF from a robot's empirical self-collision tests. */

#include <cricket/robot_info.hh>

#include <fmt/format.h>

#include <fstream>
#include <iostream>
#include <string>

int main(int argc, char **argv)
{
    if (argc < 4)
    {
        std::cerr << "usage: dump_srdf <urdf> <robot_name> <output.srdf>\n";
        return 1;
    }

    std::filesystem::path urdf_path(argv[1]);
    std::string robot_name(argv[2]);
    std::filesystem::path out_path(argv[3]);

    cricket::RobotInfo robot(urdf_path, std::nullopt, std::nullopt);

    auto adjacent = robot.get_adjacent_frames();

    std::ofstream out(out_path);
    out << "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n";
    out << "<!-- SRDF automatically generated by Cricket (https://github.com/CoMMALab/cricket) -->\n";
    out << fmt::format("<robot name=\"{}\">\n", robot_name);

    for (std::size_t a = 0; a < robot.links_with_geometry.size(); ++a)
    {
        for (std::size_t b = a + 1; b < robot.links_with_geometry.size(); ++b)
        {
            std::size_t i = robot.links_with_geometry[a];
            std::size_t j = robot.links_with_geometry[b];
            auto pair = std::make_pair(std::min(i, j), std::max(i, j));

            if (robot.allowed_link_pairs.count(pair))
            {
                continue;
            }

            std::string reason = adjacent.count(pair) ? "Adjacent" : "Never";
            out << fmt::format(
                "  <disable_collisions link1=\"{}\" link2=\"{}\" reason=\"{}\"/>\n",
                robot.model.frames[i].name,
                robot.model.frames[j].name,
                reason);
        }
    }

    out << "</robot>\n";
    out.close();

    std::cout << "Wrote " << out_path << "\n";
    return 0;
}
